volumes:
  nenga-2025-db-data:
    driver: local
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "jMJWpbHG75Gw"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      DB_NAME: "nenga"
    ports:
      - "1434:1433"
    volumes:
      - nenga-2025-db-data:/var/opt/mssql
      - ./backup:/backup
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    profiles:
      - public